export const categoryConfig = {
  Antes: { className: 'before', label: 'Antes' },
  Durante: { className: 'during', label: 'Durante' },
  Depois: { className: 'after', label: 'Depois' },
  Irregularidades: { className: 'issue', label: 'Irregularidades' },
  'Resultado final': { className: 'result', label: 'Resultado final' },
};

export const initialPhotos = [
  {
    id: 'ev-001',
    sequence: 1,
    title: 'Condição inicial do rack de rede',
    description: 'Registro geral do rack antes da intervenção, com patch cords cruzados e sem separação adequada entre os enlaces.',
    location: 'Sala de T.I. — rack principal',
    category: 'Antes',
    capturedAt: '2026-07-17T08:42:00-03:00',
    responsible: 'Rafael Teixeira',
    device: 'Samsung Galaxy S24',
    technicalNotes: 'A organização existente dificultava a identificação de portas e aumentava o tempo de diagnóstico.',
    equipment: 'Testador de rede, identificador de cabos e notebook técnico',
    situation: 'Patch cords sem padronização, curvaturas acentuadas e acesso parcial aos equipamentos.',
    action: 'Mapeamento lógico e físico de todos os pontos antes da remoção dos cabos.',
    result: 'Topologia identificada e plano de reorganização validado sem interromper os serviços críticos.',
    image: '/assets/service-before-rack.png',
    important: true,
  },
  {
    id: 'ev-002',
    sequence: 2,
    title: 'Conector RJ45 com trava danificada',
    description: 'Conector sem retenção mecânica identificado na porta de uplink, sujeito a desconexões por movimentação.',
    location: 'Sala de T.I. — switch de distribuição',
    category: 'Irregularidades',
    capturedAt: '2026-07-17T09:06:00-03:00',
    responsible: 'Rafael Teixeira',
    device: 'Samsung Galaxy S24',
    technicalNotes: 'Falha física confirmada em inspeção visual. O enlace apresentava perda intermitente sob movimentação.',
    equipment: 'Lanterna técnica e testador de continuidade RJ45',
    situation: 'Trava do conector rompida e capa de proteção deformada.',
    action: 'Substituição do patch cord por cabo certificado e novo teste de continuidade.',
    result: 'Enlace estabilizado, sem perda de pacotes no teste posterior.',
    image: '/assets/service-irregularity-cable.png',
    important: true,
  },
  {
    id: 'ev-003',
    sequence: 3,
    title: 'Reorganização dos patch cords',
    description: 'Roteamento dos cabos por guias horizontais, separando os enlaces por função e preservando o raio de curvatura.',
    location: 'Sala de T.I. — rack principal',
    category: 'Durante',
    capturedAt: '2026-07-17T10:18:00-03:00',
    responsible: 'Marcos Vieira',
    device: 'iPhone 15 Pro',
    technicalNotes: 'A reorganização foi realizada por blocos para manter os equipamentos essenciais em operação.',
    equipment: 'Guias horizontais 1U, velcro reutilizável, etiquetadora e testador de rede',
    situation: 'Cabos ocupavam a área frontal dos switches e impediam manutenção rápida.',
    action: 'Roteamento, identificação, certificação e fixação dos enlaces por grupo.',
    result: 'Acesso frontal liberado e identificação visual padronizada.',
    image: '/assets/service-during-rack.png',
    important: false,
  },
  {
    id: 'ev-004',
    sequence: 4,
    title: 'Rack organizado e operação validada',
    description: 'Vista final do rack após organização, identificação dos enlaces e testes de conectividade.',
    location: 'Sala de T.I. — rack principal',
    category: 'Resultado final',
    capturedAt: '2026-07-17T11:37:00-03:00',
    responsible: 'Marcos Vieira',
    device: 'iPhone 15 Pro',
    technicalNotes: 'Todos os enlaces ativos foram testados. Equipamentos permaneceram com status operacional normal.',
    equipment: 'Testador de rede, etiquetadora e notebook técnico',
    situation: 'Rack reorganizado após correção das irregularidades identificadas.',
    action: 'Inspeção final, teste de comunicação, conferência de portas e atualização do mapa de rede.',
    result: 'Infraestrutura organizada, documentada e com manutenção futura simplificada.',
    image: '/assets/service-after-rack.png',
    important: true,
  },
];
